alexwlchan/alexwlchan.net

.travis.yml, Gemfile, _config.yml, install_jekyll.sh
Baseline PR build: ~2:20
Related: #6.
=> A few more ideas to make the build go faster

Gemfile, Makefile, _config.yml, _includes/head.html, feeds/all.atom.xml
=> Back to doing manual generation of Atom feeds

_plugins/static_file_generator.rb, install_jekyll.sh
Resolves #23, and adds some error checking so I’ll spot it if it happens again.
=> Fix static file generation with rsync

.gitignore, .travis.yml, .travis/install.sh, .travis/run.sh, Gemfile, src/_layouts/default_xml.xml, src/_plugins/atom_feeds.rb, src/_posts/2017/2017-07-18-soundcloud-backups.md, src/feeds/all.atom.xml, tests/test_atom_feed.py, tests/test_links.py, tox.ini
And add tests in Travis that will catch any future regressions.
Resolves #31.
=> Fix issues spotted by W3C feed validator

.travis.yml, .travis/before_cache.sh, .travis/before_script.sh
Based on https://gist.github.com/hc2p/9e284cee3d585eefbc59454e44cc247a
Related: #6.
=> Add scripts for caching in Travis

src/_posts/2017/2017-09-25-source-code-on-github.md
aka the post I wrote a week ago and forgot to post 🙈
=> Add my overengineering link post

src/feeds/all.atom.xml
This is why I have custom Atom feeds, damnit!
=> Link to post targets in the Atom feed, not the post on my site

Makefile, src/_plugins/atom_feeds.rb
=> Don't include <style> tags in the RSS feed, ensure PR builds pick up issues in draft posts

src/_posts/2017/2017-10-17-control-centre.md
=> Ensure Control Centre images display correctly on mobile

Makefile
=> Run rsync inside Docker

.travis.yml
=> Try conditional build stages

Makefile
=> Exclude .DS_Store from the 'make deploy' task

analytics/.gitignore, analytics/Dockerfile, analytics/Makefile, analytics/analytics.js, analytics/analytics.py, analytics/requirements.in, analytics/requirements.txt
Oops.
This change is already deployed.
=> Don’t collect analytics for anybody who has Do Not Track enabled 🙈

Makefile, infra/alexwlchan.net.nginx.conf, src/_posts/2015/2015-03-05-python-firewall.md, src/_posts/2015/2015-09-16-http2-by-stealth.md, src/_posts/2016/2016-09-17-speech-to-text.md, src/_posts/2016/2016-09-19-silence-is-golden.md, src/tag.md, tests/conftest.py, tests/test_front_matter.py, tests/test_links.py, tests/test_nginx.py
=> Fix broken links on tag pages

src/_drafts/working-from-home.md, src/_posts/working-from-home.md, src/_scss/_settings.scss, src/_scss/_text.scss
Title might need some work, and I’m not publishing at 11:30 on a Friday.
=> New post: “A working from home experiment”

infra/alexwlchan.net.nginx.conf, tests/test_nginx.py
=> Redirect old-style tag pages to the new /tags page

.mergify.yml
Add Mergify (https://mergify.io/) to the repo.
When I’m writing posts, I typically put them in a PR (e.g. #153), and I want them to be merged when Travis goes green – if this works, they should be automatically merged (and thus posted) without any more work from me.
=> Add some Mergify config

src/_posts/2018/2018-01-20-listing-s3-keys-redux.md
=> Dead link and small code change proposal

src/404.md, src/410.md, src/_posts/2018/2018-09-24-assume-worst-intent.md, src/maths.md
This takes the number of errors from 501 to 452. Related: #144, #205.
=> Some more fixes for HTMLProofer and accessibility

src/_plugins/slides.rb, src/_posts/2018/2018-09-22-suspicious-minds.md
HTML-Proofer errors down to 321. Related: #144, #205.
=> Add alt text for the slides for my suspicious minds post

Makefile, publish_docker_image.py
=> Use pre-built Docker images in CI

src/_plugins/slides.rb, src/_posts/2018/2018-04-18-anti-social-media.md
For #144, #205. Down to 268 failures!
=> Add alt text to the slides in anti-social-media

src/_plugins/images.rb, src/_plugins/slides.rb, src/_posts/2014/2014-07-18-overcast.md, src/_posts/2014/2014-09-05-new-standing-desk.md, src/_posts/2016/2016-01-25-harry-potter-ipod.md, src/_posts/2016/2016-03-29-itunes-images-with-alfred.md, src/_posts/2017/2017-11-03-pyconuk-2017-privilege-inclusion.md, src/_posts/2017/2017-11-20-five-years-of-witch.md, src/_posts/2018/2018-04-18-anti-social-media.md, src/_posts/2018/2018-08-25-parallel-scan-scanamo.md, src/_posts/2018/2018-08-26-maps-for-pyconuk.md, src/_posts/2018/2018-09-17-lessons-in-signage.md, src/_posts/2018/2018-09-22-suspicious-minds.md, src/_posts/2018/2018-11-02-finding-unsubscribed-sns-topics.md, src/_posts/2018/2018-11-08-aberdulais-waterfall.md, src/_posts/2018/2018-12-13-getting-credentials-for-an-assumed-iam-role.md, src/_posts/2019/2019-01-31-monki-gras-the-curb-cut-effect.md
=> Add a plugin for images with alt text; start adding alt text to old images

.github/auto_merge_branch/merge_branch.py
=> Use GitHub Actions to automatically merge my pull requests

src/_includes/archive_list.html, src/_includes/post_content.html, src/_plugins/html_proofer.rb, src/_posts/2015/2015-02-22-1password.md, src/_posts/2015/2015-03-07-pygmentizr.md, src/_posts/2015/2015-05-16-one-step-paste-simulator.md, src/_posts/2015/2015-05-26-github-contributions.md, src/_posts/2016/2016-09-17-speech-to-text.md, src/_posts/2016/2016-10-21-tiling-the-plane-with-pillow.md, src/_posts/2016/2016-10-22-wallpapers-with-pillow.md, src/_posts/2017/2017-06-07-crossness-pumping-station.md, src/_posts/2017/2017-10-17-control-centre.md, src/_posts/2017/2017-10-27-pyconuk-2017-resources.md, src/_posts/2017/2017-10-28-lightning-talks.md, src/_posts/2017/2017-12-11-armed-police.md, src/_posts/2018/2018-01-25-downloading-sqs-queues.md, src/_posts/2018/2018-07-01-imac-accessory.md, src/_posts/2018/2018-10-28-horstmann-electric-7.md, src/_posts/2018/2018-10-29-unscrupulous-time-travel.md, src/_posts/2019/2019-01-22-sunlight.md, src/_posts/2019/2019-04-11-getting-a-transcript-of-a-talk-from-youtube.md, src/index.md, src/notes.md
=> Fix more bugs spotted by HTMLProofer

LICENSE, Makefile, Rakefile, azure-pipelines.yml, src/_drafts/listing-s3-keys.md, src/_includes/footer.html, src/_posts/2017/2017-07-18-listing-s3-keys.md, src/_posts/2018/2018-01-20-listing-s3-keys-redux.md
As a bonus, 580a5d0 should close #270.
=> Add a post about listing ALL THE S3 KEYS

src/_posts/2019/2019-01-28-notes-from-you-got-this.md, src/_scss/_layout.scss, src/_scss/_one_offs.scss, src/skeletor.md, src/talks/pyconuk2016.md
=> Fix a few bits of invalid HTML flagged by HTMLProofer

README.md
Another small change to test the new GitHub Actions.
=> Quote my YAML strings

src/_plugins/atom_feed_filters.rb
Closes https://github.com/alexwlchan/alexwlchan.net/issues/366
=> Scrub the blue bird from tweets from the RSS feed

src/_files/2020/download_ao3_bookmarks_from_pinboard.py, src/_posts/2020/2020-05-15-downloading-the-ao3-fics-that-i-ve-saved-in-pinboard.md, src/_scss/_updates.scss
Closes https://github.com/alexwlchan/alexwlchan.net/issues/364, among other issues
=> Fix some bugs in my AO3 script

src/_plugins/atom_feed_filters.rb
Closes https://github.com/alexwlchan/alexwlchan.net/issues/369
=> Relative URLs in the RSS feed should be absolute

src/_drafts/finding-the-months-between-two-dates-in-python.md
=> Finding the months between two dates in Python 📆 + 🐍

src/_drafts/running-concurrent-try-functions-in-scala.md, src/_layouts/default_xml.xml, src/_plugins/atom_feed_filters.rb
Plus a possible fix for https://github.com/alexwlchan/alexwlchan.net/issues/374
=> Add a quick post about concurrent Try functions in Scala

azure-pipelines.yml
See https://github.com/actions/virtual-environments/issues/3287
=> Upgrade to a supported version of Ubuntu in Azure CI

src/_plugins/linter.rb, src/_posts/2017/2017-06-07-crossness-pumping-station.md, src/_posts/2017/2017-10-25-tweets-in-keynote.md, src/_posts/2017/2017-11-20-five-years-of-witch.md
=> Add a lint that my Twitter/OpenGraph cards point at real images

src/_plugins/obfuscate_email.rb
=> Make email obfuscation more deterministic

src/_plugins/linter.rb, src/_posts/2014/2014-11-10-custom-css-resophnotes.md, src/_posts/2016/2016-10-08-worcester-28cdi-clock.md, src/_posts/2016/2016-10-16-tricity-sie454-clock.md
This starts to layer on the JSON Schema validation and apply more subtle rules based on post/page type.
=> Check that layout types are correct

src/_posts/2022/2022-07-02-saturn-v.md, src/_scss/_images_wide.scss, src/index.md
A first pass at https://github.com/alexwlchan/alexwlchan.net/issues/520
There's a bunch of rough edges, but this proves the idea is viable, and I can continue to improve it if there are obvious issues.
=> Allow marking images as full-width on narrow screens

src/_plugins/linter.rb
Closes https://github.com/alexwlchan/alexwlchan.net/issues/550
=> Add a linting rule to look for stray localhost links

.github/workflows/build_site.yml, .rubocop.yml, src/_plugins/filter_cleanup_text.rb, src/_plugins/filter_markdownify_oneline.rb, src/_plugins/filter_pretty_hr.rb, src/_plugins/filter_smartify.rb, src/_plugins/tag_details.rb
See https://jekyllrb.com/tutorials/cache-api/
I came across this in posts about speeding up Jekyll; since a lot of my text processing is nicely cacheable, it makes sense to use it and get a benefit across persistent runs.
=> Use the "new" Jekyll Cache API

Makefile, src/_plugins/theming.rb
I've started using Jekyll for books.alexwlchan.net (see https://github.com/alexwlchan/books.alexwlchan.net/pull/82), and the idea is that I can share code between my two Jekyll instances.
As I was setting up my new Jekyll instance, there were a couple of small improvements I made to the code which need to be mirrored back to this repo.
=> Copy across a couple of pieces from books.alexwlchan.net

src/_plugins/tag_picture.rb, src/_posts/2021/2021-12-31-2021-in-reading.md, src/_posts/2022/2022-12-31-2022-in-reading.md
=> Allow specifying the `height` of a picture

.github/workflows/rubocop.yml, .github/workflows/run_plugin_tests.yml, image_creator/create_images.rb
Testing whether I've fixed #711 with GitHub branch protections.
=> Deliberately introduce an error that will upset rubocop

.github/workflows/build_site.yml, src/_images/2019/K_Means_Example_Step_0.svg, src/_images/2019/K_Means_Example_Step_1.svg, src/_images/2019/K_Means_Example_Step_2.svg, src/_images/2019/K_Means_Example_Step_3.svg, src/_images/2019/K_Means_Example_Step_4.svg, src/_images/2020/rainbow_apple_logo.svg, src/_plugins/static_file_generator.rb, src/_plugins/tag_inline_svg.rb, src/_posts/2019/2019-08-19-finding-tint-colours-with-k-means.md, src/_posts/2019/2019-09-05-unpacking-compressed-archives-in-scala.md, src/_posts/2019/2019-09-12-streaming-large-s3-objects.md, src/_posts/2019/2019-09-23-triangular-coordinates-in-svg.md, src/_posts/2020/2020-03-08-stripey-flag-wallpapers.md, src/_posts/2020/2020-04-26-exploring-an-unknown-sql-server.md, src/_posts/2022/2022-09-13-graph-generative-art.md
=> Load all SVGs using inline_svg; don't copy an SVG to _site unless it's actually linked to

src/_plugins/tag_tweet.rb, src/_posts/2018/2018-09-17-lessons-in-signage.md, src/_posts/2021/2021-01-31-kempisbot.md
This is a bit of renaming and commenting for clarity, a bit of removing code. 
The key change is the introduction of a JSON schema for validating tweet metadata. Currently it's a minimal schema which will let anything through, but it's a base I can start to build on to add stronger validation in subsequent PRs.
For #733
=> Refactor and tidy up the TwitterTag class

src/_includes/contact/emails.html, src/_includes/contact/socials.html, src/_posts/2021/2021-03-07-rainbow-hearts.md, src/_posts/2022/2022-02-19-two-twitter-cards.md, src/_posts/2022/2022-08-07-spaaaaaace.md, src/_posts/2022/2022-11-28-bure-valley.md, src/_posts/2023/2023-01-15-check-for-transparency.md, src/_posts/2023/2023-03-13-cats-cross-stitch-and-copyright.md, src/_posts/2023/2023-05-11-redecorating-my-bedroom.md, src/_posts/2023/2023-09-19-obsidian-setup.md, src/_posts/2024/2024-01-07-best-age-picker.md, src/_posts/2024/2024-04-02-commons-explorer.md, src/_scss/_main.scss, src/_scss/base/code.scss, src/_scss/base/footer.scss, src/_scss/base/images_wide.scss, src/_scss/base/layout.scss, src/_scss/base/text.scss, src/_scss/mixins.scss, src/_scss/variables.scss, src/styles/style.scss
=> Continue leaning on CSS variables

src/_includes/rss_feed_entry.xml, src/_layouts/rss_feed.xml, src/atom.xml
This is some refactoring for #741 – I'm about to add a second RSS feed for the TIL page, and so I want the RSS feed to be more generic.
=> Create a basic template for RSS feeds

_config.yml, front-matter.json, src/_includes/head.html, src/_includes/nav.html, src/_includes/post_meta.html, src/_layouts/default.html, src/_layouts/til.html, src/_plugins/linter.rb, src/_scss/base/layout.scss, src/_scss/components/nav.scss, src/_scss/components/til.scss, src/_til/2024/2024-04-01-open-can-ask-questions.md, src/_til/2024/2024-04-02-send-if-modified-since-with-httpx.md, src/static/style.scss, src/til.md, src/til/atom.xml
Another piece for #741 
* Add a dedicated page and template for TIL posts
* Add an RSS feed for TIL posts
* Fix the width styling bug
* Add TIL to the top nav
=> Let's add the beginning of a TIL section

src/_includes/head.html, src/_includes/post_card.html, src/_layouts/post.html, src/_plugins/filter_cleanup_text.rb, src/_redirects, src/_til/2013/2013-05-11-rss-podcasts-tumblr.md, src/_til/2024/2024-01-02-sqlite3-context-manager-doesnt-close-connections.md, src/_til/2024/2024-01-02-use-sqlite-utils-to-convert-csv-to-sqlite.md, src/_til/2024/2024-01-03-run-random-subset-of-tests-in-pytest.md, src/_til/2024/2024-03-24-get-boto3-session.md
=> Bring across some more TILs from the old site

.gitignore, src/_plugins/pillow/get_all_image_info.py, src/_plugins/pillow/get_image_info.py, src/_plugins/pillow/get_image_info.rb, src/_tests/test_pillow.rb
This takes the cold build from ~50s to ~7s.
This is a performance improvement for #741.
=> Speed up the initial build when the image cache is cold

.github/workflows/build_site.yml, src/_plugins/card_images.rb, src/_plugins/pillow/convert_image.py, src/_plugins/pillow/create_ico_image.py, src/_plugins/pillow/create_ico_image.rb, src/_plugins/utils/tint_colors.rb
=> Fix a few lingering issues in the new Jekyll process

.github/workflows/build_site.yml, .github/workflows/run_plugin_tests.yml
Another lingering bit of build weirdness from #741; see also #781 and #777
=> Maybe I can use Nokogiri from Bundler?

src/_includes/analytics.html
I don't want my analytics snippet to be render-blocking. 😅
=> Analytics can be async; I don't need width or height any more

src/_scss/variables.scss
I'm still not 100% sold on this, but gonna give it a go and see how I feel.
=> Try using Charter as the default font for a bit

.rubocop.yml, src/_tests/test_attrs.rb, src/_tests/test_filter_cleanup_text.rb, src/_tests/test_inline_styles.rb, src/_tests/test_tag_tweet.rb, src/_tests/tests.rb
=> Re-enable or fix a bunch of previously-excluded RuboCop cops

.rubocop.yml, scripts/linter.rb, src/_plugins/inline_styles.rb, src/_plugins/visible_tags.rb
Mostly this fixes errors from the `Metrics/PerceivedComplexity` cop – and I think it was good, it found areas where the existing code was a bit complicated. Better! 💪 
For #807
=> Make a couple of improvements to reduce the RuboCop errors

scripts/linter.rb
=> Break up check_all_urls_are_hackable to improve Metrics/CyclomaticComplexity

.github/workflows/build_site.yml, src/_includes/head.html
I want to check this is being set as I expect, then I want to start using it to disable local analytics.
For https://github.com/alexwlchan/analytics.alexwlchan.net/issues/37
=> Add a JEKYLL_ENV variable to my GitHub builds

scripts/linting/check_with_html_proofer.rb, src/_plugins/static_file_generator.rb
=> Add a lint for Twitter/OpenGraph cards; fix the broken one

src/_includes/rss_feed_entry.xml
This is so I can see how many people open my links from the RSS feed.
=> Add a UTM query parameter for RSS feed entries

.rubocop.yml, src/_plugins/atom_feed_filters.rb, src/_plugins/filter_cleanup_text.rb, src/_plugins/pillow/create_ico_image.rb, src/_plugins/static_file_generator.rb, src/_plugins/utils/attrs.rb, src/_plugins/utils/pictures.rb, src/_plugins/utils/tint_colors.rb, src/_tests/tests.rb, src/contact.md
I'm going to say this closes #807 – my Ruby code is good enough, and more fiddling on it isn't actually making the site better.
=> Make a few more fixes to my RuboCop config

src/_scss/base/layout.scss, src/_scss/components/slides.css, src/_scss/components/slides.scss, src/_scss/components/tweets.scss, src/_scss/mixins.scss, src/static/style.scss
=> Remove the `centred` mixin from my Sass setup

src/_posts/2021/2021-12-31-2021-in-reading.md, src/_posts/2022/2022-10-26-accessibility-fixes.md, src/_posts/2022/2022-12-31-2022-in-reading.md, src/_posts/2023/2023-03-13-cats-cross-stitch-and-copyright.md, src/_posts/2023/2023-05-11-redecorating-my-bedroom.md, src/_posts/2023/2023-06-18-blink.md, src/_posts/2024/2024-07-04-command-icon.md, src/_posts/2024/2024-08-14-looking-at-license-plates.md, src/_posts/2024/2024-08-26-mountaintop-moments.md, src/_posts/2024/2024-09-13-digital-decluttering.md
This is a piece pull out of #904 – as part of the tag page redesign, I'm going to only show cards for featured articles, so I want a few more of them!
=> Mark more articles as featured

src/_includes/footer.html, src/_scss/components/footer.css
=> Add a "subscribe by email" link to the footer

src/_posts/2014/2014-07-11-latex-alpha.md, src/_posts/2018/2018-08-26-maps-for-pyconuk.md, src/_posts/2018/2018-09-17-lessons-in-signage.md, src/_posts/2020/2020-04-05-storing-language-vocabulary-as-a-graph.md, src/_posts/2023/2023-07-28-cloudfront-logs.md, src/_posts/2023/2023-09-28-spotting-spam-in-our-cloudfront-logs.md, src/_posts/2024/2024-06-18-flickypedia-backfillr-bot.md, src/_til/2023/2023-10-10-what-is-a-snak.md, src/_til/2023/2023-10-16-find-files-with-sdc-fields.md, src/_til/2023/2023-11-30-prefer-xml-in-the-wikimedia-apis.md, src/_til/2023/2023-12-08-convert-between-m-ids-and-filenames.md, src/_til/2024/2024-01-25-wmc-allowed-title-characters.md, src/_til/2024/2024-07-05-deleted-file-on-wikimedia-commons.md
=> Remove hyphens from a few more tags

front-matter.json, src/_includes/footer.html, src/_includes/newsletter.html, src/_layouts/default.html, src/_scss/components/footer.css, src/contact.md, src/index.md, src/subscribe.md
* Remove my social media links from my contact page
* Create a new "subscribe" page with ways to follow me
* Add the newsletter sign up to the homepage
=> Make the newsletter more visible

.github/workflows/build_site.yml
This uses a workflow established in the books.alexwlchan.net repo.
This is for #963.
=> Fix the "deploy to Linode" step

src/changelog.md
=> Create a very basic, unadvertised changelog page

scripts/linter.rb, scripts/linting/check_yaml_front_matter.rb, src/_posts/2024/2024-02-11-moving-youtube-likes.md
* Pull it out into a separate file
* Add some more comments
* Make it easier to add new checks
* Add a check for verifying colour pairs.
=> Tidy up the code for validating YAML front matter

.github/workflows/build_site.yml, .github/workflows/check_dns.yml, .github/workflows/check_website_is_up.yml, .github/workflows/merge_pull_request.yml, .github/workflows/rubocop.yml, .github/workflows/run_plugin_tests.yml, Gemfile, Gemfile.lock
=> Build the site with Ruby 3.4

src/_plugins/tag_picture.rb
=> Fix a bug that prevented dark mode variants of images

.github/workflows/build_site.yml
=> Build the site on a self-hosted runner, not GitHub's runners
