alexwlchan/alexwlchan.net

.gitignore, Makefile, _layouts/archive.html, _scss/_archive.scss, _tests/test_links.py
=> Redesign the archive pages

src/_config.yml, tests/test_links.py
I noticed they’d broken when I switched to Jekyll. Includes a test they don’t get broken again.
=> Re-enable support for footnotes

Dockerfile, Makefile, install_jekyll.sh
This just makes things a little easier locally – lockfiles and Docker images will be rebuilt automatically when their dependent resources are changed, rather than having to delete the old one first.
Plus pin to a specific Ruby version in the base image.
=> Make better use of make's dependency resolution

Makefile
This can only be run on my web server (so it’s not *that* useful for anybody else), and I still need to edit the nginx config manually, but it's another thing I don't have to do by hand.
=> Add a Make task for renewing my certbot certificates

src/_posts/2016/2016-07-28-chasing-redirects-and-url-shorteners.md, src/_posts/2016/2016-08-07-clean-up-directories.md, src/_posts/2016/2016-08-19-is-a-url-from-tumblr.md, src/_posts/2016/2016-08-31-query-strings.md, src/_posts/2016/2016-10-01-a-tally-on-the-command-line.md, src/_posts/2017/2017-01-07-scrape-logged-in-ao3.md
Turns out the templates already expected it to be there, and it was only the front matter that was broken!
Resolves #47.
=> Move minipost: into the theme block

src/_scss/_aside.scss, src/_scss/_post.scss
Resolves #42. Just an extra link underline, and some tweaked print styles. Most stuff was either good enough already, or in areas of CSS that I don’t use.
=> Tweak CSS for accessibility

src/_plugins/youtube.rb, src/_posts/2017/2017-11-03-pyconuk-2017-privilege-inclusion.md, src/feeds/all.atom.xml
feedvalidator whinges about an `<iframe>` tag appearing in the RSS; this patch flips it to be converted to an `<a>` link in its own paragraph if it ever appears in RSS.
=> Fix YouTube links in the RSS feed

.travis/run.sh, Makefile, infra/alexwlchan.net.nginx.conf, infra/docker-compose.yml, infra/nginx.conf, tests/conftest.py, tests/test_nginx.py
This patch is a precursor to some work on #113 – now there’s some nginx config that lives inside the alexwlchan.net container, which is a good place to put additional redirects and 410s.
=> Define custom nginx config for the site container

src/_includes/head.html, src/_scss/_settings.scss
The problem: every time I change my CSS, it gets cached in CloudFlare and/or browsers, so changes don't show up until the cache expires.
The solution: modify the CSS links every time I rebuild the site (by adding a timestamp), so the cache gets purged.
The idea is taken from https://stackoverflow.com/q/9638122/1558022 – there are better implementations of asset pipelines that can bust the cache only when you need it; this was the simplest thing I could think to do with the current setup.
=> Implement primitive cache busting for CSS

Dockerfile, Makefile, _config.yml, src/_plugins/static_file_generator.rb, src/_plugins/theming.rb, src/_plugins/twitter.rb
This is a bit of probably overdue refactoring – rather than rooting Jekyll in `src`, now Jekyll can run from the root of the repo.
Nothing ground-breaking, but it flushes out a few hard-coded bits of config, and means I can start using Git metadata in Jekyll processes.
I've also moved the output from `src/_site` to `_site`, so input and output don't live in the same tree.
=> Make the root of the repo be the root of the Jekyll build

src/_data/tag_aliases.yml, src/_posts/2016/2016-06-09-introduction-to-property-based-testing.md, src/tags.md, tests/test_page_content.py
And implement tag aliases so anybody who saved the link to the old "talks" tag goes to the new "slides" tag instead.
=> Consolidate the 'talks' and 'slides' tags

.mergify.yml
Because Mergify isn’t working on #180.
=> Maybe adding the /pr suffix will make the check work?

Gemfile, Gemfile.lock, _config.yml, src/robots.txt
This fixes one of the big remaining 404s, and should hopefully stop robots contributing to any of my analytics logs.
=> Add a sitemap + exclude robots from /analytics/

src/_plugins/alexwlchan_base.rb, src/_plugins/slides.rb, src/_posts/2019/2019-01-31-monki-gras-the-curb-cut-effect.md
One of the things heavily flagged by [HTMLProofer](https://alexwlchan.net/2019/02/checking-jekyll-sites-with-htmlproofer/) is the number of images that don’t have alt text (which is almost all of them!).
I don’t use images very often, but a lot of them are slides. This adds a new slide plugin that gives a way to specify alt text for a slide, and errors if it’s not provided.
This cuts the number of HTMLProofer errors from 563 to 501.
Related: #144, #205.
=> Add a {% slide %} tag that requires alt text

src/_scss/_figures.scss
This just makes it a little nicer – the image is as wide as it can fit in the window, rather than “jumping” when you cross the breakpoint.
=> Allow a gradual resizing of wide images when resizing the window

src/_includes/tweet.html, src/_plugins/twitter.rb
Liquid is where all the other templating happens. I want to tweak it shortly to support multiple images – this should make it more flexible and easier to bolt on the new bits. Templating in Ruby = 😢
=> Refactor the tweet plugin to put the HTML in a Liquid template

src/_includes/analytics.html, src/_includes/head.html, src/_layouts/default.html
You don't need it to render the page, it's not a critical resource, and the rest of the page should be fully loaded before sending any analytics off to me.
=> Move the analytics to the bottom of the page

src/_posts/2015/2015-11-30-backups-and-docker.md
Don't remember how I spotted it, but it looked incongruous.
At some point the Markdown parser changed so code blocks in indented lists are fine now. 👍
=> Fix some code formatting in an old post

Makefile, src/_plugins/static_file_generator.rb
Close #290, but properly.
As a bonus, this will break the build if I put in an invalid SVG image.
=> Minify SVGs when they get copied from `src` to `_site`

src/_includes/archive_list.html, src/_layouts/all_posts.html
* The most recent 10 posts use DD/MM dates (1 Sep, 2 Oct, 3 Nov) rather then MM/YY (Sep 2019, Oct 2019)
* There's a grey diamond between the most recent 10 and the category list
=> Tweak the appearance of the "all posts" page

src/_plugins/youtube.rb
h/t Steve Troughton-Smith: https://twitter.com/stroughtonsmith/status/1276940666933821440
> Today's protip: swap all your YouTube embeds for "http://youtube-nocookie.com". You may not even know you have tracking on your site, and Safari in macOS 11 will make it very clear
=> Use youtube-nocookie.com to reduce tracking from YouTube embeds

src/_includes/head.html, src/_plugins/all_posts_generator.rb, src/all-posts-by-tag.md, src/best-of.md
While searching in DuckDuckGo, I noticed that it's indexed the per-month and per-year archive pages, which are really specific views of the overall archive page.  They shouldn't be surfaced in search, only for people fiddling with URLs.
This patch uses <link rel="canonical"> to redirect search engines to the overall archive page, and away from the per-month/per-year pages.
=> Make /all-posts/ the canonical page for the post archive

src/_includes/head.html, src/_plugins/css_fingerprint.rb
It turns out iOS 15 ignores query parameters that aren't a key/value pair, so my cache-busting isn't actually working.  This switches to a k/v pair and embeds the MD5 fingerprint in the URL, so it should only bust the cache when the CSS actually changes.
=> Fix the CSS cache busting

src/_images/2021/non_engineers_card.svg, src/_includes/post_card.html, src/_plugins/endswith.rb, src/_plugins/inline_svg.rb
This reduces the number of round trips required to load an archive page. It’s probably a precursor to me doing cards for every page in the archive.
=> Inline SVGs on post cards

_config.yml, src/_plugins/theming.rb, src/_posts/2018/2018-08-13-inclusive-conferences.md, src/theme/style_008000.scss, src/theme/style_008921.scss, src/theme/style_0a9f9f.scss, src/theme/style_109a19.scss, src/theme/style_20883f.scss, src/theme/style_4b536e.scss, src/theme/style_531b93.scss, src/theme/style_624230.scss, src/theme/style_6c006c.scss
Previously these files had to be generated and checked in, but they're automatically generated derivatives.  It's easier to generate them at build time and dump them straight in the `_site` directory than have them cluttering up `src`.
This is part of #508.
=> Generate the per-colour SCSS files at build time

.rubocop.yml, src/_plugins/filter_cleanup_text.rb, src/_plugins/tag_download.rb, src/_plugins/tag_picture.rb, src/_plugins/theming.rb, src/_tests/test_filter_cleanup_text.rb, src/_tests/tests.rb, src/index.md
* The `<picture>` tag now uses widths instead of pixel density, which should reduce image sizes (especially on the homepage)
* Fix a couple of rubocop lints
* Add tests for the cleanup_text filters, and fix a bug where "15 minutes" became "15 15s"
=> Improve a couple of plugin things

Dockerfile, Makefile
Docker is doing… something with their free plan, I don't really know what? There's nothing keeping me on Docker Hub, so this publishes the image into GitHub Container Registry instead.
See https://github.com/docker/hub-feedback/issues/2314
=> Move the image used for builds into GitHub Container Registry

Makefile, scripts/publish_docker_image.rb
I'm now publishing linux/arm64 and linux/amd64 images, which should work on Intel and Apple Silicon Macs, respectively: see https://github.com/alexwlchan/alexwlchan.net/pkgs/container/alexwlchan.net/82198174?tag=37
I see a noticeable perf improvement to using a native image vs one in emulation, so this will be the approach for all new images.
Closes https://github.com/alexwlchan/alexwlchan.net/issues/584
=> Use `docker buildx` to publish multi-architecture images

src/_layouts/post.html
According to the MDN documentation, the "24 September 2023" format I'm using as the child text content isn't a valid date format (all the valid formats are numeric, so maybe it's to do with internationalisation?).
I suspect search engines already know how to parse this, but it seems semantically nice to provide the date in a machine-readable format here.
Closes #696.
=> Use the <time> element for timestamps on posts

src/_posts/2021/2021-12-31-2021-in-reading.md, src/_posts/2022/2022-12-31-2022-in-reading.md, src/_scss/posts/_end_of_year_books.scss
There are a couple of unnecessary wrapper &lt;div>'s which can be replaced by targeting the semantic HTML elements. As a bonus, now I can write the review text in Markdown!
=> Tidy up the HTML in my end of year book posts

src/_plugins/tag_picture.rb, src/_posts/2017/2017-07-31-backing-up-pinboard-archives.md, src/_posts/2020/2020-04-19-complex-failures.md, src/_posts/2020/2020-10-12-the-importance-of-good-error-messages.md, src/_posts/2021/2021-04-29-coloured-squares.md, src/_posts/2022/2022-04-25-lorenz-wheels.md, src/_posts/2022/2022-08-28-blink-diffs.md, src/_posts/2022/2022-10-05-circle-experiments.md, src/_posts/2022/2022-11-12-tin-anniversary.md, src/_posts/2023/2023-08-19-hester.md, src/_posts/2023/2023-09-19-obsidian-setup.md, src/_posts/2023/2023-09-20-fare-wellcome-collection.md, src/_posts/2023/2023-09-24-adding-watch-locations.md, src/_posts/2023/2023-09-28-spotting-spam-in-our-cloudfront-logs.md, src/_posts/2023/2023-10-20-forgetful-fish.md
This is a preliminary bit of refactoring I spotted while looking at #707 – there's no reason to be adding the `px` suffix if it's going to be `gsub`-ed away later, and removing it means I can remove the `gsub`.
=> Remove the 'px' suffix from the 'width' parameter on pictures

.github/workflows/merge_pull_request.py, image_creator/create_images.rb
=> Continue fiddling with the auto-merge logic

src/_includes/contact/emails.html, src/_includes/contact/socials.html, src/_posts/2022/2022-02-19-two-twitter-cards.md, src/_posts/2023/2023-01-15-check-for-transparency.md, src/_posts/2023/2023-09-19-obsidian-setup.md, src/_posts/2024/2024-01-07-best-age-picker.md, src/_scss/_settings.scss, src/_scss/base/layout.scss, src/_scss/base/text.scss, src/_scss/components/pretty_hr.scss, src/_scss/variables.scss, src/styles/style.scss
My Sass is a bit of a mess: I support custom colours per page, plus dark mode, plus a bunch of complexity I've built around the Sass preprocessor. The result is that it's hard to find where CSS stuff is defined and it's often split across multiple files. Yuck!
It's 2024. CSS variables are in [97.47% of browsers](https://caniuse.com/css-variables). They make a lot of this stuff much easier, so I should use them. (And if you're running a super old browser, you'll get the default colours and/or sans-CSS styling, which should still be fine, given I'm using a lot of semantic HTML.)
This patch takes the first step in that direction:
* It moves some of the global colours into CSS variables
* It introduces a `components` namespace for SCSS files, to make stuff easier to find
* It starts to …
=> Start using CSS variables in place of Sass

_config.yml, src/_scss/base/code.scss, src/_scss/base/footer.scss, src/_scss/base/text.scss, src/_scss/variables.scss
This gets rid of the worst of the Sass variable interpolation and replaces it with a lot of vanilla CSS. Yay!
For #741
=> Move all the Sass layout variables into CSS

_config.yml, src/_includes/eggbox.html, src/_plugins/filter_cleanup_text.rb, src/_scss/base/layout.scss
Tidying up in the aftermath of #741
=> A couple of stray tidy-up changes

src/_posts/2014/2014-05-14-part-ia-exams.md, src/_posts/2015/2015-03-29-technical-exams.md, src/_redirects, src/maths.md
This is a page tidy for #741 
I want to have less top-level pages, most of which I'm not maintaining in practice. This moves an old "exams" page into a dated post, and gets it out of the way.
=> Remove the top-level /exams/ page; make it a hidden post

.github/workflows/build_site.yml
Cleaning up a bit of lingering CI weirdness from #741.
It's meant to fix the issues with unpinned gems that I described and fixed in https://github.com/alexwlchan/alexwlchan.net/pull/777#issuecomment-2044379800. As a bonus, I suspect it will make the site quite a bit faster, because now all my installed Gems come from a Bundler cache. 💪
=> What if I rely on Nokogiri from Bundler?

.github/workflows/build_site.yml, scripts/linter.rb, scripts/linting/check_all_urls_are_hackable.rb, scripts/linting/logging.rb, scripts/linting/netlify_redirects.rb
The broken build on #811 has revealed an issue in the linting script which wasn't caught by CI, because I have the "build site" task set to skip changes to the `scripts` folder.
This patch makes the following fixes:
* The "build site" task no longer skips changes to `scripts`
* Fix the actual bug in the linting code
* Start to break up `linter.rb` into a series of smaller files, one per check, which will make it easier to run individual checks when I'm trying to debug just one of them
=> Fix an issue in the linting scripts

.rubocop.yml, scripts/linting/check_all_urls_are_hackable.rb, scripts/linting/check_with_html_proofer.rb, scripts/linting/logging.rb, scripts/linting/netlify_redirects.rb, scripts/publish_drafts.rb, src/_plugins/article_cards.rb, src/_plugins/css_fingerprint.rb, src/_plugins/filter_cleanup_text.rb, src/_plugins/filter_fix_kramdown.rb, src/_plugins/static_file_generator.rb
Running the entire command as one massive string is bad practice anyway; better to pass it as a structured series of arguments.
For #807
=> Crank down the max line length; remove an old-style command

src/_includes/rss_feed_entry.xml
This is a first step towards https://github.com/alexwlchan/alexwlchan.net/issues/787
New posts will get a trailing slash in their `<id>` element so they're the complete URL, but I can't remove this workaround until all the existing posts fall off the end of the RSS feed.
=> Add a trailing slash to the ID of new RSS feed entries

src/_scss/base/text.scss, src/_scss/components/article_cards.scss, src/_scss/components/footer.scss, src/_scss/components/nav.scss, src/_scss/components/pretty_hr.scss
I'm getting warnings when I have rules after a nested selector – moving a few rules around fixes it.
I looked for a way to get warnings-as-errors in the Sass converter, but I couldn't find it.
=> Fix a bunch of deprecation warnings from the Sass converter

src/_includes/meta.html, src/_scss/base/layout.scss, src/_scss/components/tags.scss, src/_scss/variables.scss, src/static/style.scss
These are some changes extracted from #904 that aren't blocking, so I'm going to merge and deploy these immediately.
Some CSS refactoring, and two user-visible changes:
* When you hover over tags in the title of a post, the link is now highlighted with the tint colour
* Previously the publication date was the first item in the post meta, but now I've put tags there instead
=> Make a few small tweaks to CSS and visual appearance

src/_includes/article_card.html, src/_includes/meta.html, src/_layouts/default.html, src/_posts/2024/2024-09-13-digital-decluttering.md, src/_scss/components/article_cards.scss, src/index.md, src/til.md
Another piece extracted from #904; based on ideas in #827
The date when I wrote a piece is interesting… sometimes. Some of what I write is very timely, if it's about current affairs or a very particular version of a software tool. Then you want to know when I wrote it, because it might be out-of-date. Other times it's more timeless, and could be read and written at any time. For example, "Mountaintop moments" and "Digital decluttering".
Date is easy to sort on, but it's not an especially useful way to search the site. Nobody arrives to ask "what did Alex write on 22 July 2018", because it's not a current affairs site.
Dates are still visible on individual pages, but not on the index pages.
=> De-emphasise dates throughout the site

src/_includes/meta.html, src/_includes/tag_link.html, src/_layouts/tag.html, src/_plugins/tagging.rb, src/_posts/2017/2017-02-11-backup-your-instapaper.md, src/_posts/2018/2018-05-14-google-duplex.md, src/_posts/2018/2018-08-07-finding-slow-builds-in-travis.md, src/_posts/2020/2020-07-06-changing-the-accent-colour-of-icns-icons.md, src/_til/2024/2024-01-22-beware-of-test-n-with-command-expansion.md, src/_til/2024/2024-02-22-how-to-check-when-a-cert-expires.md, src/index.md, src/tags.md
* Show all tags, and only filter by frequency for namespacing
* Namespaced tags are now at namespaced URLs, e.g. `python:pillow` is under `/tags/python/pillow/`
* Namespaced tags now link to the parent tag
=> Make a couple of improvements to tags

src/_scss/utils/functions.scss, src/_scss/variables.scss, src/static/style.scss
Previously all the default CSS variables were being re-included on any page that had a custom tint colour, because they were part of `variables.scss`. Now we don't create any CSS in that file, just export a default vars mixin that can be used once in the global stylesheet.
This reduces the average page size by ~71 bytes -- not a lot, but something!
=> Reduce the CSS at the top of tinted pages

.github/workflows/build_site.yml
This is a first step towards #933 – if I know where the site is deployed on Netlify, I can run tests against branch previews.
=> Add a GitHub Actions step to print the Netlify Deploy URL

src/_includes/article_cards.html, src/_plugins/tag_picture.rb, src/_posts/2024/2024-08-20-create-thumbnail.md, src/_scss/components/code.css, src/_scss/text_styles.css, src/_scss/text_styles.scss, src/_scss/variables.scss, src/_til/2024/2024-12-25-limits-on-visited-styles.md, src/index.md, src/static/style.scss, src/tags.md
This is a bunch of stuff extracted from my branch for "Not all blog posts are created equal", including:
* Converting `text_styles.scss` to vanilla CSS (for #893)
* Removing some redundant Liquid variables
* Fixing an error message when I try to create a `{% picture %}` which is wider than the source image
* Fixing a text sizing bug when you try to zoom in/out on the page
* Change the appearance of `:visited` links, because the current colour adjustments were quite confusing
* Add a quick TIL about the limitations of styling `:visited`
This reduces the average page size by ~5 bytes, which is to say basically nothing at all. 😢
=> Assorted improvements and style fixes

src/_includes/rss_feed_entry.xml
I had a workaround to gradually add a trailing slash to the <id> field in the RSS feed, and I was waiting for posts that had been published without trailing slash to fall off the end.  That's happened now, so I can remove the workaround.
Closes #787
=> Remove the RSS feed workaround for post <id>

scripts/linting/check_with_html_proofer.rb
Previously the local linter would fail with hundreds of errors like:
At _site/til/index.html:1:
Missing card image at http://localhost:5757/images/profile_green_square.jpg
because we weren't snipping the localhost properly, now we do.
We were snipping the host in prod, but not for local dev.  This made it harder to spot linting errors locally.
=> Fix the linter when you're running locally

scripts/measure_pageweight.rb, src/_includes/article_card.html, src/_layouts/til.html, src/_plugins/cleanup_text.rb, src/_plugins/compress_html.rb, src/_plugins/utils/markdownify_oneline.rb, src/index.md
* Remove some HTML classes that I'm not using, which are added by my syntax highlighting plugin
* Encode the JSON on the homepage in a slightly more efficient way
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>Average page size</td>
<td>14.8 KiB</td>
<td>14.6 KiB (~1%)</td>
</tr>
<tr>
<td>Articles index (<code>/articles/</code>)</td>
<td>140.6 KiB</td>
<td>138.7 KiB (~1.4%)</td>
</tr>
<tr>
<td>TIL index (<code>/til/</code>)</td>
<td>45.4 KiB</td>
<td>38.5 KiB (~15%)</td>
</tr>
<tr>
<td>Homepage (<code>/</code>)</td>
<td>27.8 KiB</td>
<td>25.0 KiB (~10%)</td>
</tr>
</table>
These are fairly small gains, but they offset the fact that these pages are gradually getting larger as I write more stuff!
I want all of these pages to be nice and fast because they're how a lot …
=> Trim the page weight slightly, especially on the homepage

src/_includes/head.html, src/_includes/head/css_variables.html, src/_includes/head/preload.html, src/_includes/head/socialgraph.html, src/_plugins/tint_colors.rb, src/_plugins/utils/tint_colors.rb, src/_posts/2025/2025-06-11-swift-bird-animation.md, src/_scss/components/footer.css, src/_scss/components/nav.css, src/_scss/variables.scss
Headers and footers now match the tint colour:
The tricky part was working out how to render black text on top of the header graphics; I always found it quite difficult to read. It finally struck me that I could just add a solid colour background of the tint colour, and it's subtle enough not to stand out too much, and now the whole page matches. 💪
=> Add dark mode variants of the headers/footers
